project:
  type: website
  output-dir: docs

website:
  title: "Leykun Getaneh Personal Website"
  navbar:
    left:
      - file: index.qmd
        text: "Home"
      - publication.qmd
      - resume.qmd
      # - file: teaching.qmd
      #   text: "Teaching"
      - sidebar:teaching
        
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/
      - icon: envelope
        href: mailto:leyk.get@gmail.com
      - icon: linkedin
        href: https://linkedin.com
    page-footer:
      right: "Built with [Quarto](https://quarto.org/)"
      left: "&copy; Copyright 2024, Leykun Getaneh"
      
  sidebar:
    - id: teaching
      title: "Teaching"
      style: "docked"
      background: light
      contents:
        - teaching.qmd
        - computing-1.qmd
        - computing-2.qmd
        - regression-analysis.qmd
        - econometrics.qmd
        - time-series-analysis.qmd
        - probability-theory.qmd
        - statistical-inference.qmd
        
format:
  html:
    theme: cerulean
#    theme: cosmo
    css: styles.css
    toc: true

editor: source

