project:
  type: website
  output-dir: docs

website:
  title: "Leykun Getaneh"
  navbar:
    left:
      - file: index.qmd
        text: "Home"
      - publication.qmd
      - resume.qmd
      - file: teaching.qmd
        text: "Teaching"
      - projects.qmd
      - blog.qmd

    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/
      - icon: envelope
        href: mailto:leyk.get@gmail.com
      - icon: linkedin
        href: https://www.linkedin.com/in/leykun-getaneh-gebeye-39a17890/
    page-footer:
      right: "Built with [Quarto](https://quarto.org/)"
      left: "&copy; Copyright 2024, Leykun Getaneh"
      

format:
  html:
    grid: 
      body-width: 2000px
      sidebar-width: 200px
      margin-width: 200px
      
    theme: 
      light: cerulean
      dark: [cosmo, theme_dark_custom.scss]
    css: styles.css
    toc: true
    citations-hover: true
    code-link: true
    code-fold: show
    code-tools: false
    code-block-border-left: "#004E4F"


editor: source

